### ISSUE TITLE
Location vs encounter.location

### ISSUE THREAD

**Issue by HanneVuegen** [hl7-be/vaccination#116]
Hello,

Can anyone explain why 'vaccination.location' is restricted, and instead, the reference to 'encounter.location' is used?

Thanks in advance,

Hanne

**Comment by HanneVuegen** [comment]
I would still like to have an explanation to why it is decided to use the encounter.location and not the vaccination.location. It seems to make it more complex then needed. Assuming that encounter.location is correct: 
- Do we then need a BeEncounter? 
- Do we then need a BeLocation 
--> For immunization/vaccination purposes the country of vaccination is in some cases mandatory. At this moment there is no Codesystem defined for the country and it is very far-fetched to go via encounter to the location...

**Comment by bdc-ehealth** [comment]
This is the reason why we did this. At that moment, the WG seemed convinced that this was the way to go: https://github.com/hl7-be/vaccination/issues/44

**Comment by HanneVuegen** [comment]
Thank you @bdc-ehealth 

Considering the scope being 'the information that is shared between systems about Vaccinations' I think it is easier to use the Bevaccination.location. The system that has more information about the encounter can still have the encounter but we cannot obligate everybody that is only interested in the BeVaccination to use the encounter information. 

I presume this is also the reason why internationally immunization keeps the location reference on this level (also the IPS version).

Any thoughts on that?

**Comment by m-shoop** [comment]
location should retain its maximum cardinality from base spec

By reducing the maximal cardinality of this element from the base spec, we reduce the possibility of re-use of software and of interoperability generally. We should strive to not exclude implementers from supporting the standard Immunization data element of location. 

Note from issue 45 and this issue I am inferring that we expect the  encounter resource to have information on the location. Since encounter has a minimum cardinality of 0, it is still valid to allow for location to be included in the returned resource for situations where no encounter is returned, as HanneVuegen suggested in the previous comment.

**Comment by KarlienHL7Belgium** [comment]
the WG decides that we keep it as it is and use BeEncounter
