### ISSUE TITLE
Adding of business rules to IG

### ISSUE THREAD

**Issue by HanneVuegen** [hl7-be/vaccination#123]
- Occurence must be before BePatient.deceased date and after BePatient.birth date
- Not possible to register 2 vaccinations of the same VaccineCode/AdministredProduct on the same date (occurence) if valid (see status)
 (1 vaccination my have a double dosage, this is 2 different vaccinations)

**Comment by KarlienHL7Belgium** [comment]
The first point seems logic, do we really need to add this to the guidance, WG decides not to.
Second point: Issue points out that it should be made impossible. Business has to look into it. WG says it is not up to us to decide this. (It should be taken into account when reconciling vaccinations). @anne nerenhausen: can you check with the business group ?

**Comment by vmichie** [comment]
1. business rule "Occurence must be before BePatient.deceased date and after BePatient.birth date"
Doctors make mistakes when registering a vaccination making adding this business rule a must. Also in the context of fraud. Vaccinations are registered by deceased patients so that the stock inventory is adjusted.

**Comment by costateixeira** [comment]
Would the enforcement of the rule reject messages? i.e. all messages that do not follow the rule will simply be ignored? will the rule be implemented in the systems and data entry? Or in the data exchange? 

As a national rule for data exchange, if we want this in the interfaces, I would start by making this a warning in the interface, so that the message can be validated, and not rejected. The real validation would be done on data entry. 

This is a simple rule and I guess it is ok to make it a more drastic  error, and completely dismiss any vaccination that is not following the rule, but i would call the attention that if this happens, then this won't prevent attempts to register vaccines. what will happen is that the vaults will never see the messages that are wrongly entered, and will therefore be unable to detect this issue or attempts of fraud. Also, in cases where the birth date or deceased date is incorrectly entered, this makes it impossible to create a vaccination for later update - all of these are examples for consideration about the impact, not necessarily saying that we must accommodate for bad data. My main point is that sometimes it is better to know bad data so that conclusions can be made, or sometimes the data may be temporarily bad and we don't want to have silent data loss due to that. It is a business decision at the end, these are arguments for consideration

**Comment by vmichie** [comment]
More info regarding business rule 2: a person receives 2 vaccinations but this is recorded as one vaccination with a double dose.

**Comment by vmichie** [comment]
@KarlienHL7Belgium : For Vitalink, this issue has priority #2

**Comment by bdc-ehealth** [comment]
WG: The business document by @annenerenhausen should be updated, and published on the "éSanté" website. The businessrules will not be added to the IG.

**Comment by HanneVuegen** [comment]
Can someone provide the link to the ésante website?
