### ISSUE TITLE
Stock management indicator in Vaccine resource.

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/vaccination#30]

**Comment by costateixeira** [comment]
What is the stock management indicator?
Can you give an example?

**Comment by bdc-ehealth** [comment]
Yes: 
If there is an exchange of vaccination data, they want to know for each vaccination whether the stock of the involved (sub-)organisation should be updated or not.

It seems that this is a thing that is specific for the use in vaccinnet.

**Comment by bdc-ehealth** [comment]
It seems somehow related to a MedicationAdministration or a MedicationDispense... But it is actually for stock management. I don't think the FHIR standard has specific resources for stock management.

**Comment by bdc-ehealth** [comment]
Vaccinnet is not taking part in the first phase of the project. We put this requirement on hold.

**Comment by KarlienHL7Belgium** [comment]
Vitalink needs to check this and come back to the WG by 31 May

**Comment by vmichie** [comment]
As a vaccinator, it must be possible to prove whether the vaccine administered comes from our own stock or is a pure registration e.g. registration of a vaccination placed abroad.

**Comment by costateixeira** [comment]
in R5, this feature is supported via InventoryReport. since we don't need to explicitly state the consumption in a separate message, nor we need the entire complexity of the InventoryReport resource, we can just use the relevant part. My analysis of this is we need a way to say in the administration "_Own stock_ is subtracted by _1_ unit". If we hardcode "1 unit", we just need a CodeableConcept for "own stock".
We can also consider an extension that explicitly states the "own stock" and "1 unit". This will allow scenarios where the number of vaccine does does not match the number of products. for example vaccine wastage (2 vials used for 1 vaccination, because one was dropped) or multidose vials (e.g. COVID vaccine)

So, suggestions:

Option 1, simplest: 
Extension "stockLocation" or similar, CodeableConcept, with an extensible binding to a valueset that contains at least "own-stock".


Option 2, most adequate(?) when inventory matters (and for vaccines, it usually does):
Complex extension with 
- stockLocation (CodeableConcept, see above)
- quantity 1..1 Quantity
- product (CodeableReference) 0..1

**Comment by HanneVuegen** [comment]
Hi all,

I don't know if it is necessary to use an extension for this. We merely need the possibility for a recorder to indicate of the vaccine came from specific source. For now we only have a Flemish governement source in mind but maybe different sources can be added in the future? 

The vaccination registration is a seperate system from the stock management system. The stock management system will provide the possibility to correct stock errors etc. We only want to make it possible to know  if a stock needs to be updated based on a vaccination registration. All information seems available in the vaccination registration so

Why do we need a seperate quantity if this is in the dosage?
Why do we need a stockLocation if it is in the encounter.organization?
Why do we need a productReference if it is in the administredproduct?

The 'FundingSource' seems to do the work as well. What are thoughts on this?

**Comment by KarlienHL7Belgium** [comment]
if we use FundingSource here, we can never use it to indicate funding afterwards ; additionally it has different semantics. Can Vitalink assess "option 1: use stockLocation" and come back next week with any objections against option 1 ?
Could we use stock or stockSource instead of stockLocation and stockQuantity (not dose as administered dose can be different from used stock quantity f.e. half dose)

**Comment by KarlienHL7Belgium** [comment]
@costateixeira will write up the extension stockSource and it will be proposed to eVax/ONE

**Comment by vmichie** [comment]
@KarlienHL7Belgium : For Vitalink, this issue has the highest priority.

**Comment by costateixeira** [comment]
Proposal is coming soon.

**Comment by bdc-ehealth** [comment]
WG: we need 2 concepts:

1) the owner: Identifier
2) location: HCO number + issuing authority

**Comment by bdc-ehealth** [comment]
WG: @costateixeira will add this to the IG.

**Comment by bdc-ehealth** [comment]
@vmichie and Didier Liebaert, for the use of the HCO number, check here: https://github.com/hl7-be/core/issues/23
